[package]
name = "spoti-together"
version = "0.1.0"
edition = "2021"

[dependencies]
imgui-rs-overlay={git = "https://github.com/lngex/imgui-rs-overlay"}
imgui = "0.12.0"
windows = { version = "0.62.2", features = ["Win32_System_DataExchange", "Win32_System_Memory", "Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_Threading"] }
reqwest = { version = "0.13", features = ["json", "blocking", "native-tls"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
urlencoding = "2"
image = "0.24"
bytes = "1"
arboard = "3"
