name: Build Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: |
          cargo install cross --locked

      - name: Build
        run: cross build --release --verbose --target x86_64-pc-windows-gnu

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jam67
          path: target/x86_64-pc-windows-gnu/release/jam67.exe
